name: Frontend CI

on:
  push:
    branches: [main, staging, develop]
    paths:
      - 'volley-app-frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main, staging, develop]
    paths:
      - 'volley-app-frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: volley-app-frontend/yarn.lock

      - name: Install dependencies
        working-directory: volley-app-frontend
        run: yarn install --frozen-lockfile

      - name: Run linter
        working-directory: volley-app-frontend
        run: yarn lint

      - name: Build
        working-directory: volley-app-frontend
        run: yarn build

